In [1]:
import numpy as np
import pandas as pd

# let's do some basic stuffs


In [2]:
a = np.array(5)
a

array(5)

In [8]:
a= np.arange(20)
a 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [9]:
a.reshape(2,5,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [10]:
print (a.shape)
print (a.ndim)
print (a.dtype.name)
print (a.itemsize)
print (a.size)

(20,)
1
int32
4
20


In [12]:
b= np.zeros((3,4))
b


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])